import Foundation
import SwiftUI

struct TarotCardData {
    static let cards: [Card] = [
        Card(name: "The Fool", imageName: "0", description: "Beginnings, innocence, spontaneity, free spirit"),
        Card(name: "The Magician", imageName: "1", description: "Manifestation, resourcefulness, power, skill"),
        Card(name: "The High Priestess", imageName: "2", description: "Intuition, unconscious knowledge, mystery"),
        Card(name: "The Empress", imageName: "3", description: "Abundance, nurturing, fertility, creativity"),
        Card(name: "The Emperor", imageName: "4", description: "Authority, structure, control, leadership"),
        Card(name: "The Hierophant", imageName: "5", description: "Tradition, conformity, spiritual wisdom"),
        Card(name: "The Lovers", imageName: "6", description: "Relationships, choices, alignment, values"),
        Card(name: "The Chariot", imageName: "7", description: "Control, willpower, victory, assertion"),
        Card(name: "Strength", imageName: "8", description: "Courage, patience, compassion, soft control"),
        Card(name: "The Hermit", imageName: "9", description: "Soul-searching, introspection, inner guidance"),
        Card(name: "The Wheel of Fortune", imageName: "10", description: "Change, cycles, fate, turning point"),
        Card(name: "Justice", imageName: "11", description: "Fairness, truth, cause and effect, law"),
        Card(name: "The Hanged Man", imageName: "12", description: "Surrender, new perspective, waiting"),
        Card(name: "Death", imageName: "13", description: "Endings, change, transformation, transition"),
        Card(name: "Temperance", imageName: "14", description: "Balance, moderation, patience, purpose"),
        Card(name: "The Devil", imageName: "15", description: "Bondage, materialism, detachment, addiction"),
        Card(name: "The Tower", imageName: "16", description: "Sudden change, upheaval, revelation, awakening"),
        Card(name: "The Star", imageName: "17", description: "Hope, inspiration, serenity, renewal"),
        Card(name: "The Moon", imageName: "18", description: "Illusion, fear, anxiety, subconscious"),
        Card(name: "The Sun", imageName: "19", description: "Success, joy, celebration, positivity"),
        Card(name: "Judgement", imageName: "20", description: "Rebirth, inner calling, absolution, awakening"),
        Card(name: "The World", imageName: "21", description: "Completion, accomplishment, travel, fulfillment"),
        Card(name: "Ace of Cups", imageName: "22", description: "New feelings, intuition, emotion, creativity"),
        Card(name: "Two of Cups", imageName: "23", description: "Partnership, mutual attraction, connection"),
        Card(name: "Three of Cups", imageName: "24", description: "Celebration, friendship, creativity, community"),
        Card(name: "Four of Cups", imageName: "25", description: "Apathy, contemplation, discontentment"),
        Card(name: "Five of Cups", imageName: "26", description: "Loss, regret, disappointment, despair"),
        Card(name: "Six of Cups", imageName: "27", description: "Nostalgia, childhood memories, innocence"),
        Card(name: "Seven of Cups", imageName: "28", description: "Choices, fantasy, illusion, opportunity"),
        Card(name: "Eight of Cups", imageName: "29", description: "Walking away, disillusionment, leaving behind"),
        Card(name: "Nine of Cups", imageName: "30", description: "Contentment, satisfaction, wish fulfillment"),
        Card(name: "Ten of Cups", imageName: "31", description: "Harmony, happiness, alignment, fulfillment"),
        Card(name: "Page of Cups", imageName: "32", description: "Creative opportunities, intuitive messages"),
        Card(name: "Knight of Cups", imageName: "33", description: "Romance, charm, imagination, seeking"),
        Card(name: "Queen of Cups", imageName: "34", description: "Compassion, caring, emotionally balanced"),
        Card(name: "King of Cups", imageName: "35", description: "Emotional balance, compassion, diplomacy"),
        Card(name: "Ace of Pentacles", imageName: "36", description: "New financial opportunity, prosperity"),
        Card(name: "Two of Pentacles", imageName: "37", description: "Balance, priorities, adaptation, juggling"),
        Card(name: "Three of Pentacles", imageName: "38", description: "Teamwork, collaboration, skill, quality"),
        Card(name: "Four of Pentacles", imageName: "39", description: "Security, control, conservatism, scarcity"),
        Card(name: "Five of Pentacles", imageName: "40", description: "Hardship, financial loss, poverty, isolation"),
        Card(name: "Six of Pentacles", imageName: "41", description: "Giving, receiving, sharing wealth, generosity"),
        Card(name: "Seven of Pentacles", imageName: "42", description: "Patience, harvest, reward, assessment"),
        Card(name: "Eight of Pentacles", imageName: "43", description: "Diligence, knowledge, detail, craftsmanship"),
        Card(name: "Nine of Pentacles", imageName: "44", description: "Luxury, self-sufficiency, financial security"),
        Card(name: "Ten of Pentacles", imageName: "45", description: "Legacy, family, establishment, wealth"),
        Card(name: "Page of Pentacles", imageName: "46", description: "Manifestation, financial opportunity, study"),
        Card(name: "Knight of Pentacles", imageName: "47", description: "Hard work, productivity, routine, conservatism"),
        Card(name: "Queen of Pentacles", imageName: "48", description: "Nurturing, practical, abundance, security"),
        Card(name: "King of Pentacles", imageName: "49", description: "Abundance, security, discipline, control"),
        Card(name: "Ace of Swords", imageName: "50", description: "Breakthrough, clarity, sharp mind, truth"),
        Card(name: "Two of Swords", imageName: "51", description: "Difficult decisions, stalemate, indecision"),
        Card(name: "Three of Swords", imageName: "52", description: "Heartbreak, emotional pain, sorrow, grief"),
        Card(name: "Four of Swords", imageName: "53", description: "Rest, restoration, contemplation, recuperation"),
        Card(name: "Five of Swords", imageName: "54", description: "Conflict, defeat, winning at all costs"),
        Card(name: "Six of Swords", imageName: "55", description: "Transition, moving on, leaving behind"),
        Card(name: "Seven of Swords", imageName: "56", description: "Deception, strategy, stealth, escape"),
        Card(name: "Eight of Swords", imageName: "57", description: "Restriction, imprisonment, self-imposed limitation"),
        Card(name: "Nine of Swords", imageName: "58", description: "Anxiety, worry, fear, nightmares"),
        Card(name: "Ten of Swords", imageName: "59", description: "Painful endings, deep wounds, betrayal, loss"),
        Card(name: "Page of Swords", imageName: "60", description: "New ideas, curiosity, communication, vigilance"),
        Card(name: "Knight of Swords", imageName: "61", description: "Action, impulsiveness, defending beliefs"),
        Card(name: "Queen of Swords", imageName: "62", description: "Independent, unbiased judgment, clear boundaries"),
        Card(name: "King of Swords", imageName: "63", description: "Mental clarity, intellectual power, authority"),
        Card(name: "Ace of Wands", imageName: "64", description: "Creation, willpower, inspiration, desire"),
        Card(name: "Two of Wands", imageName: "65", description: "Planning, making decisions, leaving comfort"),
        Card(name: "Three of Wands", imageName: "66", description: "Expansion, foresight, overseas opportunities"),
        Card(name: "Four of Wands", imageName: "67", description: "Celebration, harmony, homecoming, community"),
        Card(name: "Five of Wands", imageName: "68", description: "Competition, conflict, disagreements"),
        Card(name: "Six of Wands", imageName: "69", description: "Victory, success, public recognition, progress"),
        Card(name: "Seven of Wands", imageName: "70", description: "Challenge, competition, perseverance, defense"),
        Card(name: "Eight of Wands", imageName: "71", description: "Speed, movement, quick decisions, progress"),
        Card(name: "Nine of Wands", imageName: "72", description: "Resilience, courage, persistence, test of faith"),
        Card(name: "Ten of Wands", imageName: "73", description: "Burden, responsibility, hard work, completion"),
        Card(name: "Page of Wands", imageName: "74", description: "Exploration, excitement, discovery, free spirit"),
        Card(name: "Knight of Wands", imageName: "75", description: "Energy, passion, adventure, impulsiveness"),
        Card(name: "Queen of Wands", imageName: "76", description: "Courage, determination, joy, vibrancy"),
        Card(name: "King of Wands", imageName: "77", description: "Leadership, vision, entrepreneur, honor")
    ]
}
